import { createSlice } from '@reduxjs/toolkit';

const initialState = {
    value: 0,
}

export const counterSlice = createSlice({
    name: 'counter',
    initialState,
    reducers: {
        increment: (state) => {
            state.value += 1;
        },
        decrement: (state) => {
            state.value -= 1;
        },
        incrementByAmount: (state, action) => {
            state.value += action.payload;
        },
    },
});

// Export the actions generated by createSlice
export const { increment, decrement, incrementByAmount } = counterSlice.actions;

// Export the reducer function generated by createSlice
export default counterSlice.reducer;
